name: aprender_haciendo_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.13.8"

dependencies:
  flutter:
    sdk: flutter
  wave:
    git:
      url: git://github.com/searchy2/wave.git

  cupertino_icons: ^0.1.3
  flutter_screenutil: ^0.4.2
  firebase_core: 
  cloud_firestore: ^0.13.6
  firebase_auth: ^0.16.1
  google_sign_in: ^4.4.4
  http: ^0.12.1
  hidden_drawer_menu: ^3.0.0
  carousel_slider: ^2.2.1
  flutter_svg: ^0.17.4
  google_fonts: ^1.1.0
  modal_progress_hud: ^0.1.3
  auto_size_text: ^2.0.2
  provider: ^4.0.0
  get_it: ^1.0.3+2
  font_awesome_flutter: ^8.8.1
  # flutter_launch: ^0.2.0
  # url_launcher: ^6.0.17
  url_launcher: ^5.5.0
  rflutter_alert: ^1.0.3
  flutter_open_whatsapp: ^0.1.2
  uuid: ^2.2.0
  flutter_spinkit: ^4.1.2
  smart_select: ^3.0.3
  mailer: ^5.0.2
  flushbar: ^1.9.1

dev_dependencies:
  args: '>=1.5.0 <2.0.0'
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - images/
    - icons/
    - fonts/
    - images/45025_Coding.png
    - images/wedo.png
    - images/steamP.png
    - images/lego_M.png
    - images/lego_M.jpg
    - images/breakdance_spike.png
    - images/legoAcademy.png
    - images/firstlego.png
    - images/WRO.png
    - images/Logo_7bricks.png
    - images/Logo_7bricks_+.png
    - images/9656.png
    - images/mezcladora.png
    - images/motorizado.png
    - images/LogoAH_color.png

  fonts:
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf

    - family: Poppins-Bold
      fonts:
        - asset: fonts/Poppins-Bold.ttf

    - family: Poppins-Medium
      fonts:
        - asset: fonts/Poppins-Medium.ttf

    - family: Muli
      fonts:
        - asset: fonts/muli-extrabold.ttf

